version: "3.8"

services:
    discovery-server:
        container_name: discovery-server
        image: surajsachansudo/discovery-server:latest
        ports:
                - "8761:8761"
        environment:
          eureka.instance.hostname: discovery-server
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs


    apigateway:
        container_name: api-gateway
        image: surajsachansudo/api-gateway:latest
        ports:
                - "8082:8082"
        depends_on:
                - discovery-server
        environment:
          server.port: 8082
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs


    hotel-booking:
        container_name: hotel-booking
        image: surajsachansudo/hotel-booking:latest
        ports:
                - "8084:8084"
        depends_on:
                - discovery-server
        environment:
          server.port: 8084
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs


    flight-booking:
        container_name: flight-booking
        image: surajsachansudo/flight-booking:latest
        ports:
                - "8081:8081"
        depends_on:
                - discovery-server
        environment:
          server.port: 8081
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs


    user-service:
        container_name: user-service
        image: surajsachansudo/user-service:latest
        ports:
                - "8083:8083"
        depends_on:
                - discovery-server
        environment:
          server.port: 8083
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs



    payment-service:
        container_name: payment-service
        image: surajsachansudo/payment-service:latest
        ports:
                - "8085:8085"
        depends_on:
                - discovery-server
        environment:
          server.port: 8085
          eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
        volumes:
                - /tmp:/workspace/logs